Repository liblava/liblava, pull requests merged in 2020-03, with the labels that each got.

#14 upload texture with correct channel count
  liblava/resource/texture.cpp
Labels: bug

#16 support for specialization constants
  liblava/base/base.hpp
  liblava/block/pipeline.cpp
  liblava/block/pipeline.hpp
Labels: enhancement

#18 CMake install + find_package support
  .travis.yml
  CMakeLists.txt
  cmake/LavaConfig.cmake.in
Labels: enhancement

#19 DOCS
  DOCS.md
  README.md
Labels: good first issue
