Repository liblava/liblava, pull requests merged in 2021-07, with the labels that each got.

#66 Switch CI to GitHub Actions
  .appveyor.yml
  .github/workflows/cmake.yml
  .travis.yml
  README.md
Labels: enhancement

#59 Monomorphized Vertex Layout
  CMakeLists.txt
  README.md
  doc/Guide.md
  doc/Modules.md
  liblava-demo/generic_triangle.cpp
  liblava-demo/shapes.cpp
  liblava-demo/triangle.cpp
  liblava/core/time.hpp
  liblava/fwd.hpp
  liblava/resource/mesh.cpp
  liblava/resource/mesh.hpp
  liblava/resource/primitive.hpp
  res/generic_triangle/double_triangle.spirv
  res/generic_triangle/double_triangle.vert
  res/generic_triangle/gen_spirv.bat
  res/generic_triangle/gen_spirv.sh
  res/generic_triangle/int_triangle.spirv
  res/generic_triangle/int_triangle.vert
  res/generic_triangle/lava_triangle.spirv
  res/generic_triangle/lava_triangle.vert
  res/generic_triangle/triangle.frag
  res/generic_triangle/triangle_frag.spirv
  res/shapes/fragment.spirv
  res/shapes/gen_spirv.bat
  res/shapes/gen_spirv.sh
  res/shapes/shapes.frag
  res/shapes/shapes.vert
  res/shapes/vertex.spirv
Labels: enhancement

#67 Added camera matrix getters
  liblava/app/camera.cpp
  liblava/app/camera.hpp
Labels: enhancement

#68 Fixed mesh data regression
  liblava-demo/triangle.cpp
  liblava/resource/mesh.hpp
Labels: bug

#69 Added linking instruction to Install.md
  doc/Install.md
Labels: documentation

#70 Added a scale by vector method to mesh data
  liblava/resource/mesh.hpp
Labels: enhancement

#72 Fixed vertex buffer stride
  liblava/resource/mesh.hpp
Labels: bug

#71 Made camera controls customizable
  liblava/app/camera.cpp
  liblava/app/camera.hpp
Labels: enhancement
